apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: repl-root-certificate
  namespace: default
spec:
  secretName: tls-secret
  issuerRef:
    # Production issuer. Use certificate-staging.yaml for initial validation.
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
  commonName: repl.parthkapoor.me
  dnsNames:
    - repl.parthkapoor.me
