apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: repl-root-certificate
  namespace: default
spec:
  secretName: tls-secret
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: repl.parthkapoor.me
  dnsNames:
    - repl.parthkapoor.me
