deployment:
  kind: DaemonSet
  # hostNetwork must be nested under deployment
  hostNetwork: true

# RollingUpdate is the default strategy for DaemonSets in K8s (maxUnavailable: 1).
# You do not need to explicitly define it in the values.yaml.

ports:
  web:
    # hostPort works best when hostNetwork is true
    hostPort: 80
  websecure:
    hostPort: 443
